name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14.13
        env:
          POSTGRES_DB: rails_contributors_test
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    env:
      BUNDLE_PATH: vendor/bundle
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/rails_contributors_test

    steps:
    - uses: actions/checkout@v3

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git cmake pkg-config curl libpq-dev tzdata

    - name: Clone rails.git
      run: git clone --mirror https://github.com/rails/rails.git

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.4.5
        bundler-cache: true

    - name: Run tests
      run: bin/rails test
